name: reenactment
channels:
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blas=1.0=mkl
  - brotlipy=0.7.0=py37h27cfd23_1003
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2023.01.10=h06a4308_0
  - certifi=2022.12.7=py37h06a4308_0
  - cffi=1.15.1=py37h5eee18b_3
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - cryptography=39.0.1=py37h9ce1e76_0
  - cudatoolkit=11.3.1=h2bc3f7f_2
  - freetype=2.12.1=h4a9f257_0
  - giflib=5.2.1=h5eee18b_3
  - gmp=6.2.1=h295c915_3
  - gnutls=3.6.15=he1e5248_0
  - idna=3.4=py37h06a4308_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - jpeg=9e=h5eee18b_1
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libdeflate=1.17=h5eee18b_0
  - libffi=3.4.2=h6a678d5_6
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h7f8727e_2
  - libidn2=2.3.2=h7f8727e_0
  - libpng=1.6.39=h5eee18b_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.19.0=h5eee18b_0
  - libtiff=4.5.0=h6a678d5_2
  - libunistring=0.9.10=h27cfd23_0
  - libwebp=1.2.4=h11a3e52_1
  - libwebp-base=1.2.4=h5eee18b_1
  - lz4-c=1.9.4=h6a678d5_0
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py37h7f8727e_0
  - mkl_fft=1.3.1=py37hd3c417c_0
  - mkl_random=1.2.2=py37h51133e4_0
  - ncurses=6.4=h6a678d5_0
  - nettle=3.7.3=hbbd107a_1
  - openh264=2.1.1=h4ff587b_0
  - openssl=1.1.1t=h7f8727e_0
  - pillow=9.4.0=py37h6a678d5_0
  - pip=22.3.1=py37h06a4308_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyopenssl=23.0.0=py37h06a4308_0
  - pysocks=1.7.1=py37_1
  - python=3.7.16=h7a1cb2a_0
  - pytorch=1.12.1=py3.7_cuda11.3_cudnn8.3.2_0
  - pytorch-mutex=1.0=cuda
  - readline=8.2=h5eee18b_0
  - requests=2.28.1=py37h06a4308_0
  - setuptools=65.6.3=py37h06a4308_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.41.2=h5eee18b_0
  - tk=8.6.12=h1ccaba5_0
  - torchaudio=0.12.1=py37_cu113
  - torchvision=0.13.1=py37_cu113
  - typing_extensions=4.3.0=py37h06a4308_0
  - urllib3=1.26.14=py37h06a4308_0
  - wheel=0.38.4=py37h06a4308_0
  - xz=5.4.2=h5eee18b_0
  - zlib=1.2.13=h5eee18b_0
  - zstd=1.5.5=hc292b87_0
  - pip:
      - absl-py==1.4.0
      - aiofiles==23.1.0
      - aiohttp==3.8.4
      - aiosignal==1.3.1
      - altair==5.0.1
      - antlr4-python3-runtime==4.8
      - anyio==3.7.0
      - argparse==1.4.0
      - async-timeout==4.0.2
      - asynctest==0.13.0
      - attrs==23.1.0
      - backports-zoneinfo==0.2.1
      - blinker==1.6.2
      - blis==0.7.10
      - cachetools==5.3.1
      - catalogue==2.0.9
      - click==8.1.3
      - clip==1.0
      - coloredlogs==15.0.1
      - confection==0.1.1
      - cycler==0.11.0
      - cymem==2.0.7
      - cython==0.29.34
      - decorator==5.1.1
      - einops==0.3.0
      - exceptiongroup==1.1.1
      - face-alignment==1.3.5
      - fastai==2.7.12
      - fastapi==0.97.0
      - fastcore==1.5.29
      - fastdownload==0.0.7
      - fastprogress==1.0.3
      - ffmpeg==1.4
      - ffmpy==0.3.0
      - filelock==3.12.2
      - flatbuffers==23.3.3
      - fonttools==4.38.0
      - frozenlist==1.3.3
      - fsspec==2023.1.0
      - ftfy==6.1.1
      - future==0.18.3
      - gitdb==4.0.10
      - gitpython==3.1.31
      - google-auth==2.20.0
      - google-auth-oauthlib==0.4.6
      - gradio==3.34.0
      - gradio-client==0.2.6
      - grpcio==1.56.0
      - h11==0.14.0
      - httpcore==0.17.2
      - httpx==0.24.1
      - huggingface-hub==0.15.1
      - humanfriendly==10.0
      - imageio==2.28.1
      - imageio-ffmpeg==0.4.8
      - importlib-metadata==6.6.0
      - importlib-resources==5.12.0
      - jinja2==3.1.2
      - joblib==1.3.1
      - jsonschema==4.17.3
      - kiwisolver==1.4.4
      - langcodes==3.3.0
      - linkify-it-py==2.0.2
      - llvmlite==0.39.1
      - markdown==3.4.3
      - markdown-it-py==2.2.0
      - markupsafe==2.1.3
      - matplotlib==3.5.3
      - mdit-py-plugins==0.3.3
      - mdurl==0.1.2
      - mpmath==1.3.0
      - multidict==6.0.4
      - munch==2.5.0
      - murmurhash==1.0.9
      - networkx==2.6.3
      - numba==0.56.4
      - numpy==1.21.6
      - oauthlib==3.2.2
      - omegaconf==2.1.1
      - onnxruntime==1.14.1
      - open-clip-torch==2.0.2
      - opencv-python==4.7.0.72
      - orjson==3.9.1
      - packaging==23.1
      - pandas==1.3.5
      - pathy==0.10.2
      - pkgutil-resolve-name==1.3.10
      - preshed==3.0.8
      - protobuf==3.20.3
      - pyarrow==12.0.1
      - pyasn1==0.5.0
      - pyasn1-modules==0.3.0
      - pydantic==1.10.9
      - pydeck==0.8.1b0
      - pydeprecate==0.3.1
      - pydub==0.25.1
      - pygments==2.15.1
      - pympler==1.0.1
      - pyparsing==3.0.9
      - pyrsistent==0.19.3
      - python-dateutil==2.8.2
      - python-multipart==0.0.6
      - pytorch-lightning==1.5.0
      - pytube==15.0.0
      - pytz==2023.3
      - pywavelets==1.3.0
      - pyyaml==6.0
      - regex==2023.6.3
      - requests-oauthlib==1.3.1
      - rich==13.4.2
      - rsa==4.9
      - scikit-image==0.19.3
      - scikit-learn==1.0.2
      - scipy==1.7.3
      - semantic-version==2.10.0
      - semver==3.0.1
      - smart-open==6.3.0
      - smmap==5.0.0
      - sniffio==1.3.0
      - spacy==3.6.1
      - spacy-legacy==3.0.12
      - spacy-loggers==1.0.4
      - srsly==2.4.7
      - starlette==0.27.0
      - streamlit==1.12.1
      - sympy==1.10.1
      - tensorboard==2.11.2
      - tensorboard-data-server==0.6.1
      - tensorboard-plugin-wit==1.8.1
      - tensorboardx==2.6
      - thinc==8.1.12
      - threadpoolctl==3.1.0
      - tifffile==2021.11.2
      - tokenizers==0.12.1
      - toml==0.10.2
      - toolz==0.12.0
      - torchmetrics==0.11.4
      - tornado==6.2
      - tqdm==4.65.0
      - transformers==4.19.2
      - typer==0.9.0
      - tzlocal==5.0.1
      - uc-micro-py==1.0.2
      - uvicorn==0.22.0
      - validators==0.20.0
      - wasabi==1.1.2
      - watchdog==3.0.0
      - wcwidth==0.2.6
      - websockets==11.0.3
      - werkzeug==2.2.3
      - yarl==1.9.2
      - zipp==3.15.0
prefix: /home/avlab/anaconda3/envs/reenactment
